# Usage: docker-compose up -d
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    hostname: mariadb
    environment:
      - MARIADB_USER=mantisbt
      - MARIADB_PASSWORD=mantisbt
      - MARIADB_DATABASE=bugtracker
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - ALLOW_EMPTY_PASSWORD=no
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami'
  
  mantisbt:
    image: vimagick/mantisbt:latest
    hostname: mantisbt
    ports:
      - "80:80"
    depends_on:
      - mariadb
    links:
      - mariadb
    restart: always

volumes:
  mariadb_data:
    driver: local